// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: appoinments.sql

package sqlc

import (
	"context"

	"github.com/alexisTrejo11/Clinic-Vet-API/db/models"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAppoinments = `-- name: CountAppoinments :one
SELECT COUNT(*) FROM appoinments
WHERE deleted_at IS NULL
`

func (q *Queries) CountAppoinments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppoinmentsByDateRange = `-- name: CountAppoinmentsByDateRange :one
SELECT COUNT(*) FROM appoinments
WHERE schedule_date BETWEEN $1 AND $2
AND deleted_at IS NULL
`

type CountAppoinmentsByDateRangeParams struct {
	ScheduleDate   pgtype.Timestamptz
	ScheduleDate_2 pgtype.Timestamptz
}

func (q *Queries) CountAppoinmentsByDateRange(ctx context.Context, arg CountAppoinmentsByDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinmentsByDateRange, arg.ScheduleDate, arg.ScheduleDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppoinmentsByOwnerID = `-- name: CountAppoinmentsByOwnerID :one
SELECT COUNT(*) FROM appoinments
WHERE owner_id = $1
AND deleted_at IS NULL
`

func (q *Queries) CountAppoinmentsByOwnerID(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinmentsByOwnerID, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppoinmentsByPetID = `-- name: CountAppoinmentsByPetID :one
SELECT COUNT(*) FROM appoinments
WHERE pet_id = $1
AND deleted_at IS NULL
`

func (q *Queries) CountAppoinmentsByPetID(ctx context.Context, petID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinmentsByPetID, petID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppoinmentsByStatus = `-- name: CountAppoinmentsByStatus :one
SELECT COUNT(*) FROM appoinments
WHERE status = $1
AND deleted_at IS NULL
`

func (q *Queries) CountAppoinmentsByStatus(ctx context.Context, status models.AppointmentStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinmentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppoinmentsByVeterinarianID = `-- name: CountAppoinmentsByVeterinarianID :one
SELECT COUNT(*) FROM appoinments
WHERE veterinarian_id = $1
AND deleted_at IS NULL
`

func (q *Queries) CountAppoinmentsByVeterinarianID(ctx context.Context, veterinarianID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAppoinmentsByVeterinarianID, veterinarianID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppoinment = `-- name: CreateAppoinment :one
INSERT INTO appoinments (
    clinic_service, 
    schedule_date, 
    status, 
    reason, 
    notes, 
    owner_id, 
    veterinarian_id,
    pet_id,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL
) RETURNING id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at
`

type CreateAppoinmentParams struct {
	ClinicService  models.ClinicService
	ScheduleDate   pgtype.Timestamptz
	Status         models.AppointmentStatus
	Reason         string
	Notes          pgtype.Text
	OwnerID        int32
	VeterinarianID int32
	PetID          int32
}

func (q *Queries) CreateAppoinment(ctx context.Context, arg CreateAppoinmentParams) (Appoinment, error) {
	row := q.db.QueryRow(ctx, createAppoinment,
		arg.ClinicService,
		arg.ScheduleDate,
		arg.Status,
		arg.Reason,
		arg.Notes,
		arg.OwnerID,
		arg.VeterinarianID,
		arg.PetID,
	)
	var i Appoinment
	err := row.Scan(
		&i.ID,
		&i.ClinicService,
		&i.ScheduleDate,
		&i.Status,
		&i.Reason,
		&i.Notes,
		&i.OwnerID,
		&i.VeterinarianID,
		&i.PetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAppoinment = `-- name: DeleteAppoinment :exec
UPDATE appoinments SET
    deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteAppoinment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAppoinment, id)
	return err
}

const getAppoinmentByID = `-- name: GetAppoinmentByID :one
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments 
WHERE id = $1 
AND deleted_at IS NULL
`

func (q *Queries) GetAppoinmentByID(ctx context.Context, id int32) (Appoinment, error) {
	row := q.db.QueryRow(ctx, getAppoinmentByID, id)
	var i Appoinment
	err := row.Scan(
		&i.ID,
		&i.ClinicService,
		&i.ScheduleDate,
		&i.Status,
		&i.Reason,
		&i.Notes,
		&i.OwnerID,
		&i.VeterinarianID,
		&i.PetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAppoinments = `-- name: ListAppoinments :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAppoinmentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAppoinments(ctx context.Context, arg ListAppoinmentsParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppoinmentsByDateRange = `-- name: ListAppoinmentsByDateRange :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments
WHERE schedule_date BETWEEN $1 AND $2
AND deleted_at IS NULL
ORDER BY schedule_date DESC LIMIT $3 OFFSET $4
`

type ListAppoinmentsByDateRangeParams struct {
	ScheduleDate   pgtype.Timestamptz
	ScheduleDate_2 pgtype.Timestamptz
	Limit          int32
	Offset         int32
}

func (q *Queries) ListAppoinmentsByDateRange(ctx context.Context, arg ListAppoinmentsByDateRangeParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinmentsByDateRange,
		arg.ScheduleDate,
		arg.ScheduleDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppoinmentsByOwnerID = `-- name: ListAppoinmentsByOwnerID :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments 
WHERE owner_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAppoinmentsByOwnerIDParams struct {
	OwnerID int32
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAppoinmentsByOwnerID(ctx context.Context, arg ListAppoinmentsByOwnerIDParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinmentsByOwnerID, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppoinmentsByPetID = `-- name: ListAppoinmentsByPetID :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments
WHERE pet_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAppoinmentsByPetIDParams struct {
	PetID  int32
	Limit  int32
	Offset int32
}

func (q *Queries) ListAppoinmentsByPetID(ctx context.Context, arg ListAppoinmentsByPetIDParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinmentsByPetID, arg.PetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppoinmentsByStatus = `-- name: ListAppoinmentsByStatus :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments
WHERE status = $1
AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAppoinmentsByStatusParams struct {
	Status models.AppointmentStatus
	Limit  int32
	Offset int32
}

func (q *Queries) ListAppoinmentsByStatus(ctx context.Context, arg ListAppoinmentsByStatusParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinmentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppoinmentsByVeterinarianID = `-- name: ListAppoinmentsByVeterinarianID :many
SELECT id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at FROM appoinments
WHERE veterinarian_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAppoinmentsByVeterinarianIDParams struct {
	VeterinarianID int32
	Limit          int32
	Offset         int32
}

func (q *Queries) ListAppoinmentsByVeterinarianID(ctx context.Context, arg ListAppoinmentsByVeterinarianIDParams) ([]Appoinment, error) {
	rows, err := q.db.Query(ctx, listAppoinmentsByVeterinarianID, arg.VeterinarianID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appoinment
	for rows.Next() {
		var i Appoinment
		if err := rows.Scan(
			&i.ID,
			&i.ClinicService,
			&i.ScheduleDate,
			&i.Status,
			&i.Reason,
			&i.Notes,
			&i.OwnerID,
			&i.VeterinarianID,
			&i.PetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppoinment = `-- name: UpdateAppoinment :one
UPDATE appoinments SET
    clinic_service = $2,
    schedule_date = $3,
    status = $4,
    reason = $5,
    notes = $6,
    owner_id = $7,
    veterinarian_id = $8,
    pet_id = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, clinic_service, schedule_date, status, reason, notes, owner_id, veterinarian_id, pet_id, created_at, updated_at, deleted_at
`

type UpdateAppoinmentParams struct {
	ID             int32
	ClinicService  models.ClinicService
	ScheduleDate   pgtype.Timestamptz
	Status         models.AppointmentStatus
	Reason         string
	Notes          pgtype.Text
	OwnerID        int32
	VeterinarianID int32
	PetID          int32
}

func (q *Queries) UpdateAppoinment(ctx context.Context, arg UpdateAppoinmentParams) (Appoinment, error) {
	row := q.db.QueryRow(ctx, updateAppoinment,
		arg.ID,
		arg.ClinicService,
		arg.ScheduleDate,
		arg.Status,
		arg.Reason,
		arg.Notes,
		arg.OwnerID,
		arg.VeterinarianID,
		arg.PetID,
	)
	var i Appoinment
	err := row.Scan(
		&i.ID,
		&i.ClinicService,
		&i.ScheduleDate,
		&i.Status,
		&i.Reason,
		&i.Notes,
		&i.OwnerID,
		&i.VeterinarianID,
		&i.PetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
