// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"clinic-vet-api/db/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID                  int32
	UserID              int32
	Street              string
	City                string
	State               string
	ZipCode             string
	Country             string
	BuildingType        string
	BuildingOuterNumber string
	BuildingInnerNumber string
	IsDefault           bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	Version             int32
}

type Appointment struct {
	ID            int32
	ClinicService models.ClinicService
	ScheduledDate pgtype.Timestamptz
	Status        models.AppointmentStatus
	Notes         pgtype.Text
	CustomerID    int32
	PetID         int32
	EmployeeID    pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Customer struct {
	ID          int32
	FirstName   string
	LastName    string
	Photo       string
	DateOfBirth pgtype.Date
	Gender      models.PersonGender
	UserID      pgtype.Int4
	IsActive    bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Employee struct {
	ID                int32
	FirstName         string
	LastName          string
	Gender            models.PersonGender
	DateOfBirth       pgtype.Date
	Photo             string
	LicenseNumber     string
	Speciality        models.VeterinarianSpeciality
	YearsOfExperience int32
	IsActive          bool
	UserID            pgtype.Int4
	ScheduleJson      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamp
}

type MedicalSession struct {
	ID              int32
	PetID           int32
	CustomerID      int32
	EmployeeID      int32
	AppointmentID   pgtype.Int4
	ClinicService   models.ClinicService
	VisitDate       pgtype.Timestamptz
	VisitType       string
	Diagnosis       pgtype.Text
	Notes           pgtype.Text
	Treatment       pgtype.Text
	Condition       pgtype.Text
	Weight          pgtype.Numeric
	Temperature     pgtype.Numeric
	HeartRate       pgtype.Int4
	RespiratoryRate pgtype.Int4
	Symptoms        pgtype.Text
	Medications     pgtype.Text
	FollowUpDate    pgtype.Timestamptz
	IsEmergency     pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type Medication struct {
	ID                   int32
	Name                 string
	ActiveIngredient     pgtype.Text
	Presentation         pgtype.Text
	Unit                 pgtype.Text
	RequiresPrescription pgtype.Bool
	SpeciesWarnings      pgtype.Text
	IsActive             pgtype.Bool
	CreatedAt            pgtype.Timestamptz
}

type Notification struct {
	ID               int32
	UserID           int32
	Title            string
	Subject          string
	Message          string
	Token            string
	NotificationType string
	Channel          string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Payment struct {
	ID               int32
	Amount           pgtype.Numeric
	Currency         string
	Status           models.PaymentStatus
	Method           models.PaymentMethod
	MedSessionID     pgtype.Int4
	TransactionID    pgtype.Text
	Description      pgtype.Text
	DueDate          pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	RefundedAt       pgtype.Timestamptz
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	PaidByCustomerID pgtype.Int4
	InvoiceID        pgtype.Text
	RefundAmount     pgtype.Numeric
	FailureReason    pgtype.Text
}

type Pet struct {
	ID                    int32
	Name                  string
	Photo                 pgtype.Text
	Species               string
	Breed                 pgtype.Text
	Age                   pgtype.Int2
	Gender                pgtype.Text
	Color                 pgtype.Text
	Microchip             pgtype.Text
	BloodType             pgtype.Text
	IsNeutered            pgtype.Bool
	CustomerID            int32
	IsActive              bool
	Allergies             pgtype.Text
	CurrentMedications    pgtype.Text
	SpecialNeeds          pgtype.Text
	FeedingInstructions   pgtype.Text
	BehavioralNotes       pgtype.Text
	VeterinaryContact     pgtype.Text
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type PetBehavioralNote struct {
	ID      int32
	PetID   int32
	Note    string
	NotedAt pgtype.Timestamptz
	NotedBy pgtype.Int4
}

type PetChipImplant struct {
	ID              int32
	PetID           int32
	ImplantDate     pgtype.Date
	ImplantLocation pgtype.Text
	ChipNumber      pgtype.Text
	ImplantedBy     pgtype.Int4
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type PetDeworming struct {
	ID               int32
	PetID            int32
	MedicationName   string
	AdministeredDate pgtype.Date
	NextDueDate      pgtype.Date
	AdministeredBy   pgtype.Int4
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type PetFeedingInstruction struct {
	ID                  int32
	PetID               int32
	FoodBrand           pgtype.Text
	FoodType            pgtype.Text
	AmountPerServing    pgtype.Text
	Frequency           pgtype.Text
	SpecialInstructions pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type PetVaccination struct {
	ID               int32
	PetID            int32
	VaccineName      string
	AdministeredDate pgtype.Date
	NextDueDate      pgtype.Date
	AdministeredBy   pgtype.Int4
	BatchNumber      pgtype.Text
	VaccineType      string
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PetVaccinationHistory struct {
	PetID         int32
	VaccinationID int32
	SessionID     int32
	VisitDate     pgtype.Timestamptz
	VaccineName   string
	DiseaseTarget pgtype.Text
	DoseNumber    int32
	BatchNumber   pgtype.Text
	NextDoseDate  pgtype.Date
	ReactionNotes pgtype.Text
	VetID         int32
}

type ServiceCatalog struct {
	ID              int32
	Name            string
	Category        string
	Description     pgtype.Text
	BasePrice       pgtype.Numeric
	DurationMin     pgtype.Int4
	RequiresFasting pgtype.Bool
	IsActive        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
}

type SessionAttachment struct {
	ID          int32
	SessionID   int32
	FileType    string
	FileUrl     string
	Description pgtype.Text
	UploadedBy  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type SessionPrescription struct {
	ID           int32
	SessionID    int32
	MedicationID int32
	Dosage       string
	Frequency    string
	DurationDays pgtype.Int4
	Route        pgtype.Text
	Instructions pgtype.Text
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	CreatedAt    pgtype.Timestamptz
}

type SessionService struct {
	ID               int32
	SessionID        int32
	ServiceCatalogID int32
	Quantity         pgtype.Numeric
	PriceApplied     pgtype.Numeric
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type SessionSurgery struct {
	ID              int32
	SessionID       int32
	ProcedureName   string
	AnesthesiaType  pgtype.Text
	AnesthesiaAgent pgtype.Text
	PreOpNotes      pgtype.Text
	IntraOpNotes    pgtype.Text
	PostOpNotes     pgtype.Text
	DurationMinutes pgtype.Int4
	Outcome         pgtype.Text
	SurgeonID       pgtype.Int4
	CreatedAt       pgtype.Timestamptz
}

type SessionVaccination struct {
	ID               int32
	SessionID        int32
	VaccineCatalogID int32
	BatchNumber      pgtype.Text
	DoseNumber       int32
	ExpirationDate   pgtype.Date
	SiteOfInjection  pgtype.Text
	NextDoseDate     pgtype.Date
	ReactionNotes    pgtype.Text
	AdministeredBy   pgtype.Int4
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID                          int32
	Email                       pgtype.Text
	PhoneNumber                 pgtype.Text
	HashedPassword              pgtype.Text
	Role                        string
	Status                      string
	Name                        string
	Gender                      pgtype.Text
	PhotoUrl                    pgtype.Text
	Bio                         pgtype.Text
	DateOfBirth                 pgtype.Date
	OauthProvider               string
	OauthProviderID             pgtype.Text
	OauthAccessToken            pgtype.Text
	OauthRefreshToken           pgtype.Text
	OauthTokenExpiry            pgtype.Timestamptz
	EmailVerified               pgtype.Bool
	TwoFaMethod                 string
	TwoFaSecret                 pgtype.Text
	TwoFaEnabled                pgtype.Bool
	TwoFaEnabledAt              pgtype.Timestamptz
	TwoFaBackupCodes            []string
	TwoFaBackupCodesGeneratedAt pgtype.Timestamptz
	Last2faCodeUsedAt           pgtype.Timestamptz
	LastLogin                   pgtype.Timestamptz
	LoginAttempts               pgtype.Int4
	LockedUntil                 pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
}

type VaccineCatalog struct {
	ID            int32
	Name          string
	Manufacturer  pgtype.Text
	Species       pgtype.Text
	DiseaseTarget pgtype.Text
	TotalDoses    pgtype.Int4
	ScheduleDays  []int32
	Notes         pgtype.Text
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
}
