// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServiceCatalogAll = `-- name: CountServiceCatalogAll :one
SELECT COUNT(*) FROM service_catalog WHERE is_active = TRUE
`

func (q *Queries) CountServiceCatalogAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceCatalogAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServiceCatalogByCategory = `-- name: CountServiceCatalogByCategory :one
SELECT COUNT(*) FROM service_catalog WHERE is_active = TRUE AND category = $1
`

func (q *Queries) CountServiceCatalogByCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceCatalogByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceCatalog = `-- name: CreateServiceCatalog :one
INSERT INTO service_catalog (name, category, description, base_price, duration_min, requires_fasting, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, category, description, base_price, duration_min, requires_fasting, is_active, created_at
`

type CreateServiceCatalogParams struct {
	Name            string
	Category        string
	Description     pgtype.Text
	BasePrice       pgtype.Numeric
	DurationMin     pgtype.Int4
	RequiresFasting pgtype.Bool
	IsActive        pgtype.Bool
}

func (q *Queries) CreateServiceCatalog(ctx context.Context, arg CreateServiceCatalogParams) (ServiceCatalog, error) {
	row := q.db.QueryRow(ctx, createServiceCatalog,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.BasePrice,
		arg.DurationMin,
		arg.RequiresFasting,
		arg.IsActive,
	)
	var i ServiceCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.BasePrice,
		&i.DurationMin,
		&i.RequiresFasting,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceCatalogByID = `-- name: DeleteServiceCatalogByID :exec
DELETE FROM service_catalog WHERE id = $1
`

func (q *Queries) DeleteServiceCatalogByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteServiceCatalogByID, id)
	return err
}

const findServiceCatalogAll = `-- name: FindServiceCatalogAll :many
SELECT id, name, category, description, base_price, duration_min, requires_fasting, is_active, created_at FROM service_catalog WHERE is_active = TRUE ORDER BY name LIMIT $1 OFFSET $2
`

type FindServiceCatalogAllParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FindServiceCatalogAll(ctx context.Context, arg FindServiceCatalogAllParams) ([]ServiceCatalog, error) {
	rows, err := q.db.Query(ctx, findServiceCatalogAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCatalog
	for rows.Next() {
		var i ServiceCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.BasePrice,
			&i.DurationMin,
			&i.RequiresFasting,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findServiceCatalogByCategory = `-- name: FindServiceCatalogByCategory :many
SELECT id, name, category, description, base_price, duration_min, requires_fasting, is_active, created_at FROM service_catalog WHERE is_active = TRUE AND category = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type FindServiceCatalogByCategoryParams struct {
	Category string
	Limit    int32
	Offset   int32
}

func (q *Queries) FindServiceCatalogByCategory(ctx context.Context, arg FindServiceCatalogByCategoryParams) ([]ServiceCatalog, error) {
	rows, err := q.db.Query(ctx, findServiceCatalogByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCatalog
	for rows.Next() {
		var i ServiceCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.BasePrice,
			&i.DurationMin,
			&i.RequiresFasting,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findServiceCatalogByID = `-- name: FindServiceCatalogByID :one
SELECT id, name, category, description, base_price, duration_min, requires_fasting, is_active, created_at FROM service_catalog WHERE id = $1
`

func (q *Queries) FindServiceCatalogByID(ctx context.Context, id int32) (ServiceCatalog, error) {
	row := q.db.QueryRow(ctx, findServiceCatalogByID, id)
	var i ServiceCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.BasePrice,
		&i.DurationMin,
		&i.RequiresFasting,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateServiceCatalog = `-- name: UpdateServiceCatalog :one
UPDATE service_catalog
SET name = $2, category = $3, description = $4, base_price = $5, duration_min = $6, requires_fasting = $7, is_active = $8
WHERE id = $1
RETURNING id, name, category, description, base_price, duration_min, requires_fasting, is_active, created_at
`

type UpdateServiceCatalogParams struct {
	ID              int32
	Name            string
	Category        string
	Description     pgtype.Text
	BasePrice       pgtype.Numeric
	DurationMin     pgtype.Int4
	RequiresFasting pgtype.Bool
	IsActive        pgtype.Bool
}

func (q *Queries) UpdateServiceCatalog(ctx context.Context, arg UpdateServiceCatalogParams) (ServiceCatalog, error) {
	row := q.db.QueryRow(ctx, updateServiceCatalog,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.BasePrice,
		arg.DurationMin,
		arg.RequiresFasting,
		arg.IsActive,
	)
	var i ServiceCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.BasePrice,
		&i.DurationMin,
		&i.RequiresFasting,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
