// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionService = `-- name: CreateSessionService :one
INSERT INTO session_services (session_id, service_catalog_id, quantity, price_applied, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, service_catalog_id, quantity, price_applied, notes, created_at
`

type CreateSessionServiceParams struct {
	SessionID        int32
	ServiceCatalogID int32
	Quantity         pgtype.Numeric
	PriceApplied     pgtype.Numeric
	Notes            pgtype.Text
}

func (q *Queries) CreateSessionService(ctx context.Context, arg CreateSessionServiceParams) (SessionService, error) {
	row := q.db.QueryRow(ctx, createSessionService,
		arg.SessionID,
		arg.ServiceCatalogID,
		arg.Quantity,
		arg.PriceApplied,
		arg.Notes,
	)
	var i SessionService
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ServiceCatalogID,
		&i.Quantity,
		&i.PriceApplied,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionServiceByID = `-- name: DeleteSessionServiceByID :exec
DELETE FROM session_services WHERE id = $1
`

func (q *Queries) DeleteSessionServiceByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSessionServiceByID, id)
	return err
}

const deleteSessionServicesBySessionID = `-- name: DeleteSessionServicesBySessionID :exec
DELETE FROM session_services WHERE session_id = $1
`

func (q *Queries) DeleteSessionServicesBySessionID(ctx context.Context, sessionID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionServicesBySessionID, sessionID)
	return err
}

const findSessionServiceByID = `-- name: FindSessionServiceByID :one
SELECT id, session_id, service_catalog_id, quantity, price_applied, notes, created_at FROM session_services WHERE id = $1
`

func (q *Queries) FindSessionServiceByID(ctx context.Context, id int32) (SessionService, error) {
	row := q.db.QueryRow(ctx, findSessionServiceByID, id)
	var i SessionService
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ServiceCatalogID,
		&i.Quantity,
		&i.PriceApplied,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionServicesBySessionID = `-- name: FindSessionServicesBySessionID :many
SELECT id, session_id, service_catalog_id, quantity, price_applied, notes, created_at FROM session_services WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) FindSessionServicesBySessionID(ctx context.Context, sessionID int32) ([]SessionService, error) {
	rows, err := q.db.Query(ctx, findSessionServicesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionService
	for rows.Next() {
		var i SessionService
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ServiceCatalogID,
			&i.Quantity,
			&i.PriceApplied,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionService = `-- name: UpdateSessionService :one
UPDATE session_services
SET session_id = $2, service_catalog_id = $3, quantity = $4, price_applied = $5, notes = $6
WHERE id = $1
RETURNING id, session_id, service_catalog_id, quantity, price_applied, notes, created_at
`

type UpdateSessionServiceParams struct {
	ID               int32
	SessionID        int32
	ServiceCatalogID int32
	Quantity         pgtype.Numeric
	PriceApplied     pgtype.Numeric
	Notes            pgtype.Text
}

func (q *Queries) UpdateSessionService(ctx context.Context, arg UpdateSessionServiceParams) (SessionService, error) {
	row := q.db.QueryRow(ctx, updateSessionService,
		arg.ID,
		arg.SessionID,
		arg.ServiceCatalogID,
		arg.Quantity,
		arg.PriceApplied,
		arg.Notes,
	)
	var i SessionService
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ServiceCatalogID,
		&i.Quantity,
		&i.PriceApplied,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
