// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersBySpec = `-- name: CountUsersBySpec :one
SELECT COUNT(*) FROM users
WHERE 
    ($1::INT IS NULL OR id = $1)
    AND ($2::TEXT IS NULL OR $2 = '' OR email = $2)
    AND ($3::TEXT IS NULL OR $3 = '' OR phone_number = $3)
    AND ($4::TEXT IS NULL OR $4 = '' OR role = $4)
    AND ($5::TEXT IS NULL OR $5 = '' OR status = $5)
    AND ($6::TEXT IS NULL OR $6 = '' OR oauth_provider = $6)
    AND ($7::BOOLEAN IS NULL OR email_verified = $7)
    AND ($8::BOOLEAN IS NULL OR two_fa_enabled = $8)
    AND ($9::TEXT IS NULL OR $9 = '' OR name ILIKE '%' || $9 || '%')
    AND ($10::TIMESTAMP IS NULL OR created_at >= $10)
    AND ($11::TIMESTAMP IS NULL OR created_at <= $11)
    AND ($12::TIMESTAMP IS NULL OR last_login >= $12)
    AND deleted_at IS NULL
`

type CountUsersBySpecParams struct {
	Column1  int32
	Column2  string
	Column3  string
	Column4  string
	Column5  string
	Column6  string
	Column7  bool
	Column8  bool
	Column9  string
	Column10 pgtype.Timestamp
	Column11 pgtype.Timestamp
	Column12 pgtype.Timestamp
}

func (q *Queries) CountUsersBySpec(ctx context.Context, arg CountUsersBySpecParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersBySpec,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, 
    phone_number, 
    hashed_password, 
    role, 
    status,
    name,
    gender,
    photo_url,
    bio,
    date_of_birth,
    oauth_provider,
    oauth_provider_id,
    oauth_access_token,
    oauth_refresh_token,
    oauth_token_expiry,
    email_verified,
    two_fa_method,
    two_fa_secret,
    two_fa_enabled,
    two_fa_enabled_at,
    two_fa_backup_codes,
    two_fa_backup_codes_generated_at,
    last_2fa_code_used_at,
    last_login,
    login_attempts,
    locked_until,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) RETURNING id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email                       pgtype.Text
	PhoneNumber                 pgtype.Text
	HashedPassword              pgtype.Text
	Role                        string
	Status                      string
	Name                        string
	Gender                      pgtype.Text
	PhotoUrl                    pgtype.Text
	Bio                         pgtype.Text
	DateOfBirth                 pgtype.Date
	OauthProvider               string
	OauthProviderID             pgtype.Text
	OauthAccessToken            pgtype.Text
	OauthRefreshToken           pgtype.Text
	OauthTokenExpiry            pgtype.Timestamptz
	EmailVerified               pgtype.Bool
	TwoFaMethod                 string
	TwoFaSecret                 pgtype.Text
	TwoFaEnabled                pgtype.Bool
	TwoFaEnabledAt              pgtype.Timestamptz
	TwoFaBackupCodes            []string
	TwoFaBackupCodesGeneratedAt pgtype.Timestamptz
	Last2faCodeUsedAt           pgtype.Timestamptz
	LastLogin                   pgtype.Timestamptz
	LoginAttempts               pgtype.Int4
	LockedUntil                 pgtype.Timestamptz
}

// ========================================
// CREATE & UPDATE OPERATIONS
// ========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PhoneNumber,
		arg.HashedPassword,
		arg.Role,
		arg.Status,
		arg.Name,
		arg.Gender,
		arg.PhotoUrl,
		arg.Bio,
		arg.DateOfBirth,
		arg.OauthProvider,
		arg.OauthProviderID,
		arg.OauthAccessToken,
		arg.OauthRefreshToken,
		arg.OauthTokenExpiry,
		arg.EmailVerified,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaEnabled,
		arg.TwoFaEnabledAt,
		arg.TwoFaBackupCodes,
		arg.TwoFaBackupCodesGeneratedAt,
		arg.Last2faCodeUsedAt,
		arg.LastLogin,
		arg.LoginAttempts,
		arg.LockedUntil,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const existsUserByCustomerID = `-- name: ExistsUserByCustomerID :one
SELECT COUNT(*) > 0
FROM users u
INNER JOIN customers c ON u.id = c.user_id
WHERE c.id = $1
AND u.deleted_at IS NULL
AND c.deleted_at IS NULL
`

func (q *Queries) ExistsUserByCustomerID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByCustomerID, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT COUNT(*) > 0 FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsUserByEmployeeID = `-- name: ExistsUserByEmployeeID :one
SELECT COUNT(*) > 0
FROM users u
INNER JOIN employees e ON u.id = e.user_id
WHERE e.id = $1
AND u.deleted_at IS NULL
AND e.deleted_at IS NULL
`

func (q *Queries) ExistsUserByEmployeeID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmployeeID, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsUserByID = `-- name: ExistsUserByID :one

SELECT COUNT(*) > 0 FROM users
WHERE id = $1
AND deleted_at IS NULL
`

// ========================================
// EXISTS OPERATIONS
// ========================================
func (q *Queries) ExistsUserByID(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByID, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsUserByPhoneNumber = `-- name: ExistsUserByPhoneNumber :one
SELECT COUNT(*) > 0 FROM users
WHERE phone_number = $1
AND deleted_at IS NULL
`

func (q *Queries) ExistsUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByPhoneNumber, phoneNumber)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findUserByCustomerID = `-- name: FindUserByCustomerID :one
SELECT u.id, u.email, u.phone_number, u.hashed_password, u.role, u.status, u.name, u.gender, u.photo_url, u.bio, u.date_of_birth, u.oauth_provider, u.oauth_provider_id, u.oauth_access_token, u.oauth_refresh_token, u.oauth_token_expiry, u.email_verified, u.two_fa_method, u.two_fa_secret, u.two_fa_enabled, u.two_fa_enabled_at, u.two_fa_backup_codes, u.two_fa_backup_codes_generated_at, u.last_2fa_code_used_at, u.last_login, u.login_attempts, u.locked_until, u.created_at, u.updated_at, u.deleted_at
FROM users u
INNER JOIN customers c ON u.id = c.user_id
WHERE c.id = $1
AND u.deleted_at IS NULL
AND c.deleted_at IS NULL
`

func (q *Queries) FindUserByCustomerID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserByCustomerID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByEmployeeID = `-- name: FindUserByEmployeeID :one
SELECT u.id, u.email, u.phone_number, u.hashed_password, u.role, u.status, u.name, u.gender, u.photo_url, u.bio, u.date_of_birth, u.oauth_provider, u.oauth_provider_id, u.oauth_access_token, u.oauth_refresh_token, u.oauth_token_expiry, u.email_verified, u.two_fa_method, u.two_fa_secret, u.two_fa_enabled, u.two_fa_enabled_at, u.two_fa_backup_codes, u.two_fa_backup_codes_generated_at, u.last_2fa_code_used_at, u.last_login, u.login_attempts, u.locked_until, u.created_at, u.updated_at, u.deleted_at
FROM users u
INNER JOIN employees e ON u.id = e.user_id
WHERE e.id = $1
AND u.deleted_at IS NULL
AND e.deleted_at IS NULL
`

func (q *Queries) FindUserByEmployeeID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmployeeID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one

SELECT id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at FROM users 
WHERE id = $1 
AND deleted_at IS NULL
`

// ========================================
// FIND OPERATIONS
// ========================================
func (q *Queries) FindUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByOAuthProvider = `-- name: FindUserByOAuthProvider :one
SELECT id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at FROM users
WHERE oauth_provider = $1
AND oauth_provider_id = $2
AND deleted_at IS NULL
`

type FindUserByOAuthProviderParams struct {
	OauthProvider   string
	OauthProviderID pgtype.Text
}

func (q *Queries) FindUserByOAuthProvider(ctx context.Context, arg FindUserByOAuthProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByOAuthProvider, arg.OauthProvider, arg.OauthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByPhoneNumber = `-- name: FindUserByPhoneNumber :one
SELECT id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at FROM users
WHERE phone_number = $1
AND deleted_at IS NULL
`

func (q *Queries) FindUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUsersBySpec = `-- name: FindUsersBySpec :many
SELECT id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at FROM users
WHERE 
    ($1::INT IS NULL OR id = $1)
    AND ($2::TEXT IS NULL OR $2 = '' OR email = $2)
    AND ($3::TEXT IS NULL OR $3 = '' OR phone_number = $3)
    AND ($4::TEXT IS NULL OR $4 = '' OR role = $4)
    AND ($5::TEXT IS NULL OR $5 = '' OR status = $5)
    AND ($6::TEXT IS NULL OR $6 = '' OR oauth_provider = $6)
    AND ($7::BOOLEAN IS NULL OR email_verified = $7)
    AND ($8::BOOLEAN IS NULL OR two_fa_enabled = $8)
    AND ($9::TEXT IS NULL OR $9 = '' OR name ILIKE '%' || $9 || '%')
    AND ($10::TIMESTAMP IS NULL OR created_at >= $10)
    AND ($11::TIMESTAMP IS NULL OR created_at <= $11)
    AND ($12::TIMESTAMP IS NULL OR last_login >= $12)
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $13 OFFSET $14
`

type FindUsersBySpecParams struct {
	Column1  int32
	Column2  string
	Column3  string
	Column4  string
	Column5  string
	Column6  string
	Column7  bool
	Column8  bool
	Column9  string
	Column10 pgtype.Timestamp
	Column11 pgtype.Timestamp
	Column12 pgtype.Timestamp
	Limit    int32
	Offset   int32
}

func (q *Queries) FindUsersBySpec(ctx context.Context, arg FindUsersBySpecParams) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsersBySpec,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.HashedPassword,
			&i.Role,
			&i.Status,
			&i.Name,
			&i.Gender,
			&i.PhotoUrl,
			&i.Bio,
			&i.DateOfBirth,
			&i.OauthProvider,
			&i.OauthProviderID,
			&i.OauthAccessToken,
			&i.OauthRefreshToken,
			&i.OauthTokenExpiry,
			&i.EmailVerified,
			&i.TwoFaMethod,
			&i.TwoFaSecret,
			&i.TwoFaEnabled,
			&i.TwoFaEnabledAt,
			&i.TwoFaBackupCodes,
			&i.TwoFaBackupCodesGeneratedAt,
			&i.Last2faCodeUsedAt,
			&i.LastLogin,
			&i.LoginAttempts,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec

UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// ========================================
// DELETE & RESTORE OPERATIONS
// ========================================
func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    email = COALESCE($2, email),
    phone_number = COALESCE($3, phone_number),
    hashed_password = COALESCE($4, hashed_password),
    role = COALESCE($5, role),
    status = COALESCE($6, status),
    name = COALESCE($7, name),
    gender = COALESCE($8, gender),
    photo_url = COALESCE($9, photo_url),
    bio = COALESCE($10, bio),
    date_of_birth = COALESCE($11, date_of_birth),
    oauth_provider = COALESCE($12, oauth_provider),
    oauth_provider_id = COALESCE($13, oauth_provider_id),
    oauth_access_token = COALESCE($14, oauth_access_token),
    oauth_refresh_token = COALESCE($15, oauth_refresh_token),
    oauth_token_expiry = COALESCE($16, oauth_token_expiry),
    email_verified = COALESCE($17, email_verified),
    two_fa_method = COALESCE($18, two_fa_method),
    two_fa_secret = COALESCE($19, two_fa_secret),
    two_fa_enabled = COALESCE($20, two_fa_enabled),
    two_fa_enabled_at = COALESCE($21, two_fa_enabled_at),
    two_fa_backup_codes = COALESCE($22, two_fa_backup_codes),
    two_fa_backup_codes_generated_at = COALESCE($23, two_fa_backup_codes_generated_at),
    last_2fa_code_used_at = COALESCE($24, last_2fa_code_used_at),
    last_login = COALESCE($25, last_login),
    login_attempts = COALESCE($26, login_attempts),
    locked_until = COALESCE($27, locked_until),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, phone_number, hashed_password, role, status, name, gender, photo_url, bio, date_of_birth, oauth_provider, oauth_provider_id, oauth_access_token, oauth_refresh_token, oauth_token_expiry, email_verified, two_fa_method, two_fa_secret, two_fa_enabled, two_fa_enabled_at, two_fa_backup_codes, two_fa_backup_codes_generated_at, last_2fa_code_used_at, last_login, login_attempts, locked_until, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                          int32
	Email                       pgtype.Text
	PhoneNumber                 pgtype.Text
	HashedPassword              pgtype.Text
	Role                        string
	Status                      string
	Name                        string
	Gender                      pgtype.Text
	PhotoUrl                    pgtype.Text
	Bio                         pgtype.Text
	DateOfBirth                 pgtype.Date
	OauthProvider               string
	OauthProviderID             pgtype.Text
	OauthAccessToken            pgtype.Text
	OauthRefreshToken           pgtype.Text
	OauthTokenExpiry            pgtype.Timestamptz
	EmailVerified               pgtype.Bool
	TwoFaMethod                 string
	TwoFaSecret                 pgtype.Text
	TwoFaEnabled                pgtype.Bool
	TwoFaEnabledAt              pgtype.Timestamptz
	TwoFaBackupCodes            []string
	TwoFaBackupCodesGeneratedAt pgtype.Timestamptz
	Last2faCodeUsedAt           pgtype.Timestamptz
	LastLogin                   pgtype.Timestamptz
	LoginAttempts               pgtype.Int4
	LockedUntil                 pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.HashedPassword,
		arg.Role,
		arg.Status,
		arg.Name,
		arg.Gender,
		arg.PhotoUrl,
		arg.Bio,
		arg.DateOfBirth,
		arg.OauthProvider,
		arg.OauthProviderID,
		arg.OauthAccessToken,
		arg.OauthRefreshToken,
		arg.OauthTokenExpiry,
		arg.EmailVerified,
		arg.TwoFaMethod,
		arg.TwoFaSecret,
		arg.TwoFaEnabled,
		arg.TwoFaEnabledAt,
		arg.TwoFaBackupCodes,
		arg.TwoFaBackupCodesGeneratedAt,
		arg.Last2faCodeUsedAt,
		arg.LastLogin,
		arg.LoginAttempts,
		arg.LockedUntil,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.HashedPassword,
		&i.Role,
		&i.Status,
		&i.Name,
		&i.Gender,
		&i.PhotoUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthTokenExpiry,
		&i.EmailVerified,
		&i.TwoFaMethod,
		&i.TwoFaSecret,
		&i.TwoFaEnabled,
		&i.TwoFaEnabledAt,
		&i.TwoFaBackupCodes,
		&i.TwoFaBackupCodesGeneratedAt,
		&i.Last2faCodeUsedAt,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
