// Code generated by MockGen. DO NOT EDIT.
// Source: sqlc/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/alexisTrejo11/Clinic-Vet-API/sqlc"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockQuerier) ActivateUser(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateuserDomain.
func (mr *MockQuerierMockRecorder) ActivateUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockQuerier)(nil).ActivateUser), ctx, id)
}

// CreateOwner mocks base method.
func (m *MockQuerier) CreateOwner(ctx context.Context, arg sqlc.CreateOwnerParams) (sqlc.CreateOwnerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwner", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateOwnerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOwner indicates an expected call of CreateOwner.
func (mr *MockQuerierMockRecorder) CreateOwner(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwner", reflect.TypeOf((*MockQuerier)(nil).CreateOwner), ctx, arg)
}

// CreatePet mocks base method.
func (m *MockQuerier) CreatePet(ctx context.Context, arg sqlc.CreatePetParams) (sqlc.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePet", ctx, arg)
	ret0, _ := ret[0].(sqlc.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePet indicates an expected call of CreatePet.
func (mr *MockQuerierMockRecorder) CreatePet(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePet", reflect.TypeOf((*MockQuerier)(nil).CreatePet), ctx, arg)
}

// CreateVeterinarian mocks base method.
func (m *MockQuerier) CreateVeterinarian(ctx context.Context, arg sqlc.CreateVeterinarianParams) (sqlc.Veterinarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVeterinarian", ctx, arg)
	ret0, _ := ret[0].(sqlc.Veterinarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVeterinarian indicates an expected call of CreateVeterinarian.
func (mr *MockQuerierMockRecorder) CreateVeterinarian(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVeterinarian", reflect.TypeOf((*MockQuerier)(nil).CreateVeterinarian), ctx, arg)
}

// DeactivateUser mocks base method.
func (m *MockQuerier) DeactivateUser(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateuserDomain.
func (mr *MockQuerierMockRecorder) DeactivateUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockQuerier)(nil).DeactivateUser), ctx, id)
}

// DeleteOwner mocks base method.
func (m *MockQuerier) DeleteOwner(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOwner", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOwner indicates an expected call of DeleteOwner.
func (mr *MockQuerierMockRecorder) DeleteOwner(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOwner", reflect.TypeOf((*MockQuerier)(nil).DeleteOwner), ctx, id)
}

// DeletePet mocks base method.
func (m *MockQuerier) DeletePet(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePet", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePet indicates an expected call of DeletePet.
func (mr *MockQuerierMockRecorder) DeletePet(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePet", reflect.TypeOf((*MockQuerier)(nil).DeletePet), ctx, id)
}

// ExistByID mocks base method.
func (m *MockQuerier) ExistByID(ctx context.Context, id int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByID indicates an expected call of ExistByID.
func (mr *MockQuerierMockRecorder) ExistByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByID", reflect.TypeOf((*MockQuerier)(nil).ExistByID), ctx, id)
}

// ExistByPhoneNumber mocks base method.
func (m *MockQuerier) ExistByPhoneNumber(ctx context.Context, phoneNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistByPhoneNumber", ctx, phoneNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistByPhoneNumber indicates an expected call of ExistByPhoneNumber.
func (mr *MockQuerierMockRecorder) ExistByPhoneNumber(ctx, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistByPhoneNumber", reflect.TypeOf((*MockQuerier)(nil).ExistByPhoneNumber), ctx, phoneNumber)
}

// GetOwnerByID mocks base method.
func (m *MockQuerier) GetOwnerByID(ctx context.Context, id int32) (sqlc.GetOwnerByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByID", ctx, id)
	ret0, _ := ret[0].(sqlc.GetOwnerByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByID indicates an expected call of GetOwnerByID.
func (mr *MockQuerierMockRecorder) GetOwnerByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByID", reflect.TypeOf((*MockQuerier)(nil).GetOwnerByID), ctx, id)
}

// GetOwnerByPhone mocks base method.
func (m *MockQuerier) GetOwnerByPhone(ctx context.Context, phoneNumber string) (sqlc.GetOwnerByPhoneRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByPhone", ctx, phoneNumber)
	ret0, _ := ret[0].(sqlc.GetOwnerByPhoneRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByPhone indicates an expected call of GetOwnerByPhone.
func (mr *MockQuerierMockRecorder) GetOwnerByPhone(ctx, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByPhone", reflect.TypeOf((*MockQuerier)(nil).GetOwnerByPhone), ctx, phoneNumber)
}

// GetOwnerByUserID mocks base method.
func (m *MockQuerier) GetOwnerByUserID(ctx context.Context, userID pgtype.Int4) (sqlc.GetOwnerByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlc.GetOwnerByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByUserID indicates an expected call of GetOwnerByUserID.
func (mr *MockQuerierMockRecorder) GetOwnerByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByUserID", reflect.TypeOf((*MockQuerier)(nil).GetOwnerByUserID), ctx, userID)
}

// GetPetByID mocks base method.
func (m *MockQuerier) GetPetByID(ctx context.Context, id int32) (sqlc.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPetByID indicates an expected call of GetPetByID.
func (mr *MockQuerierMockRecorder) GetPetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPetByID", reflect.TypeOf((*MockQuerier)(nil).GetPetByID), ctx, id)
}

// GetPetsByOwnerID mocks base method.
func (m *MockQuerier) GetPetsByOwnerID(ctx context.Context, ownerID int32) ([]sqlc.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPetsByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].([]sqlc.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPetsByOwnerID indicates an expected call of GetPetsByOwnerID.
func (mr *MockQuerierMockRecorder) GetPetsByOwnerID(ctx, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPetsByOwnerID", reflect.TypeOf((*MockQuerier)(nil).GetPetsByOwnerID), ctx, ownerID)
}

// GetVeterinarianById mocks base method.
func (m *MockQuerier) GetVeterinarianById(ctx context.Context, id int32) (sqlc.Veterinarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVeterinarianById", ctx, id)
	ret0, _ := ret[0].(sqlc.Veterinarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVeterinarianById indicates an expected call of GetVeterinarianById.
func (mr *MockQuerierMockRecorder) GetVeterinarianById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVeterinarianById", reflect.TypeOf((*MockQuerier)(nil).GetVeterinarianById), ctx, id)
}

// ListOwners mocks base method.
func (m *MockQuerier) ListOwners(ctx context.Context, arg sqlc.ListOwnersParams) ([]sqlc.ListOwnersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwners", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListOwnersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwners indicates an expected call of ListOwners.
func (mr *MockQuerierMockRecorder) ListOwners(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwners", reflect.TypeOf((*MockQuerier)(nil).ListOwners), ctx, arg)
}

// ListPets mocks base method.
func (m *MockQuerier) ListPets(ctx context.Context) ([]sqlc.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPets", ctx)
	ret0, _ := ret[0].([]sqlc.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPets indicates an expected call of ListPets.
func (mr *MockQuerierMockRecorder) ListPets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPets", reflect.TypeOf((*MockQuerier)(nil).ListPets), ctx)
}

// ListVeterinarians mocks base method.
func (m *MockQuerier) ListVeterinarians(ctx context.Context, arg sqlc.ListVeterinariansParams) ([]sqlc.Veterinarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVeterinarians", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Veterinarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVeterinarians indicates an expected call of ListVeterinarians.
func (mr *MockQuerierMockRecorder) ListVeterinarians(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVeterinarians", reflect.TypeOf((*MockQuerier)(nil).ListVeterinarians), ctx, arg)
}

// SoftDeleteVeterinarian mocks base method.
func (m *MockQuerier) SoftDeleteVeterinarian(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteVeterinarian", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteVeterinarian indicates an expected call of SoftDeleteVeterinarian.
func (mr *MockQuerierMockRecorder) SoftDeleteVeterinarian(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteVeterinarian", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteVeterinarian), ctx, id)
}

// UpdateOwner mocks base method.
func (m *MockQuerier) UpdateOwner(ctx context.Context, arg sqlc.UpdateOwnerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwner", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOwner indicates an expected call of UpdateOwner.
func (mr *MockQuerierMockRecorder) UpdateOwner(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwner", reflect.TypeOf((*MockQuerier)(nil).UpdateOwner), ctx, arg)
}

// UpdatePet mocks base method.
func (m *MockQuerier) UpdatePet(ctx context.Context, arg sqlc.UpdatePetParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePet", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockQuerierMockRecorder) UpdatePet(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockQuerier)(nil).UpdatePet), ctx, arg)
}

// UpdateVeterinarian mocks base method.
func (m *MockQuerier) UpdateVeterinarian(ctx context.Context, arg sqlc.UpdateVeterinarianParams) (sqlc.Veterinarian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVeterinarian", ctx, arg)
	ret0, _ := ret[0].(sqlc.Veterinarian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVeterinarian indicates an expected call of UpdateVeterinarian.
func (mr *MockQuerierMockRecorder) UpdateVeterinarian(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVeterinarian", reflect.TypeOf((*MockQuerier)(nil).UpdateVeterinarian), ctx, arg)
}

// WithTx mocks base method.
func (m *MockQuerier) WithTx(tx pgx.Tx) *sqlc.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*sqlc.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockQuerierMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockQuerier)(nil).WithTx), tx)
}
