// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: medications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMedicationsAll = `-- name: CountMedicationsAll :one
SELECT COUNT(*) FROM medications WHERE is_active = TRUE
`

func (q *Queries) CountMedicationsAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMedicationsAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMedicationsSearch = `-- name: CountMedicationsSearch :one
SELECT COUNT(*) FROM medications WHERE is_active = TRUE AND (name ILIKE '%' || $1 || '%' OR active_ingredient ILIKE '%' || $1 || '%')
`

func (q *Queries) CountMedicationsSearch(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countMedicationsSearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active, created_at
`

type CreateMedicationParams struct {
	Name                 string
	ActiveIngredient     pgtype.Text
	Presentation         pgtype.Text
	Unit                 pgtype.Text
	RequiresPrescription pgtype.Bool
	SpeciesWarnings      pgtype.Text
	IsActive             pgtype.Bool
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, createMedication,
		arg.Name,
		arg.ActiveIngredient,
		arg.Presentation,
		arg.Unit,
		arg.RequiresPrescription,
		arg.SpeciesWarnings,
		arg.IsActive,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ActiveIngredient,
		&i.Presentation,
		&i.Unit,
		&i.RequiresPrescription,
		&i.SpeciesWarnings,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedicationByID = `-- name: DeleteMedicationByID :exec
DELETE FROM medications WHERE id = $1
`

func (q *Queries) DeleteMedicationByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMedicationByID, id)
	return err
}

const findMedicationByID = `-- name: FindMedicationByID :one
SELECT id, name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active, created_at FROM medications WHERE id = $1
`

func (q *Queries) FindMedicationByID(ctx context.Context, id int32) (Medication, error) {
	row := q.db.QueryRow(ctx, findMedicationByID, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ActiveIngredient,
		&i.Presentation,
		&i.Unit,
		&i.RequiresPrescription,
		&i.SpeciesWarnings,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const findMedicationsAll = `-- name: FindMedicationsAll :many
SELECT id, name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active, created_at FROM medications WHERE is_active = TRUE ORDER BY name LIMIT $1 OFFSET $2
`

type FindMedicationsAllParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FindMedicationsAll(ctx context.Context, arg FindMedicationsAllParams) ([]Medication, error) {
	rows, err := q.db.Query(ctx, findMedicationsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medication
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ActiveIngredient,
			&i.Presentation,
			&i.Unit,
			&i.RequiresPrescription,
			&i.SpeciesWarnings,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMedications = `-- name: SearchMedications :many
SELECT id, name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active, created_at FROM medications WHERE is_active = TRUE AND (name ILIKE '%' || $1 || '%' OR active_ingredient ILIKE '%' || $1 || '%') ORDER BY name LIMIT $2 OFFSET $3
`

type SearchMedicationsParams struct {
	Column1 pgtype.Text
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchMedications(ctx context.Context, arg SearchMedicationsParams) ([]Medication, error) {
	rows, err := q.db.Query(ctx, searchMedications, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medication
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ActiveIngredient,
			&i.Presentation,
			&i.Unit,
			&i.RequiresPrescription,
			&i.SpeciesWarnings,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedication = `-- name: UpdateMedication :one
UPDATE medications
SET name = $2, active_ingredient = $3, presentation = $4, unit = $5, requires_prescription = $6, species_warnings = $7, is_active = $8
WHERE id = $1
RETURNING id, name, active_ingredient, presentation, unit, requires_prescription, species_warnings, is_active, created_at
`

type UpdateMedicationParams struct {
	ID                   int32
	Name                 string
	ActiveIngredient     pgtype.Text
	Presentation         pgtype.Text
	Unit                 pgtype.Text
	RequiresPrescription pgtype.Bool
	SpeciesWarnings      pgtype.Text
	IsActive             pgtype.Bool
}

func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, updateMedication,
		arg.ID,
		arg.Name,
		arg.ActiveIngredient,
		arg.Presentation,
		arg.Unit,
		arg.RequiresPrescription,
		arg.SpeciesWarnings,
		arg.IsActive,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ActiveIngredient,
		&i.Presentation,
		&i.Unit,
		&i.RequiresPrescription,
		&i.SpeciesWarnings,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
