// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const countNotificationsByChannel = `-- name: CountNotificationsByChannel :one
SELECT COUNT(*) FROM notifications
WHERE channel = $1
`

func (q *Queries) CountNotificationsByChannel(ctx context.Context, channel string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByChannel, channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationsByType = `-- name: CountNotificationsByType :one
SELECT COUNT(*) FROM notifications
WHERE notification_type = $1
`

func (q *Queries) CountNotificationsByType(ctx context.Context, notificationType string) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByType, notificationType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationsByUserID = `-- name: CountNotificationsByUserID :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, title, subject, message, token, notification_type, channel
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, title, subject, message, token, notification_type, channel,
          created_at, updated_at
`

type CreateNotificationParams struct {
	UserID           int32
	Title            string
	Subject          string
	Message          string
	Token            string
	NotificationType string
	Channel          string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Subject,
		arg.Message,
		arg.Token,
		arg.NotificationType,
		arg.Channel,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Subject,
		&i.Message,
		&i.Token,
		&i.NotificationType,
		&i.Channel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findNotificationsByChannel = `-- name: FindNotificationsByChannel :many
SELECT id, user_id, title, subject, message, token, notification_type, channel,
       created_at, updated_at
FROM notifications
WHERE channel = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindNotificationsByChannelParams struct {
	Channel string
	Limit   int32
	Offset  int32
}

func (q *Queries) FindNotificationsByChannel(ctx context.Context, arg FindNotificationsByChannelParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findNotificationsByChannel, arg.Channel, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Subject,
			&i.Message,
			&i.Token,
			&i.NotificationType,
			&i.Channel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationsByType = `-- name: FindNotificationsByType :many
SELECT id, user_id, title, subject, message, token, notification_type, channel,
       created_at, updated_at
FROM notifications
WHERE notification_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindNotificationsByTypeParams struct {
	NotificationType string
	Limit            int32
	Offset           int32
}

func (q *Queries) FindNotificationsByType(ctx context.Context, arg FindNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findNotificationsByType, arg.NotificationType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Subject,
			&i.Message,
			&i.Token,
			&i.NotificationType,
			&i.Channel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotificationsByUserID = `-- name: FindNotificationsByUserID :many
SELECT id, user_id, title, subject, message, token, notification_type, channel,
       created_at, updated_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindNotificationsByUserIDParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

func (q *Queries) FindNotificationsByUserID(ctx context.Context, arg FindNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Subject,
			&i.Message,
			&i.Token,
			&i.NotificationType,
			&i.Channel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, title, subject, message, token, notification_type, channel,
       created_at, updated_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Subject,
		&i.Message,
		&i.Token,
		&i.NotificationType,
		&i.Channel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
