// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_surgeries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionSurgery = `-- name: CreateSessionSurgery :one
INSERT INTO session_surgeries (
    session_id, procedure_name, anesthesia_type, anesthesia_agent,
    pre_op_notes, intra_op_notes, post_op_notes, duration_minutes, outcome, surgeon_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, session_id, procedure_name, anesthesia_type, anesthesia_agent, pre_op_notes, intra_op_notes, post_op_notes, duration_minutes, outcome, surgeon_id, created_at
`

type CreateSessionSurgeryParams struct {
	SessionID       int32
	ProcedureName   string
	AnesthesiaType  pgtype.Text
	AnesthesiaAgent pgtype.Text
	PreOpNotes      pgtype.Text
	IntraOpNotes    pgtype.Text
	PostOpNotes     pgtype.Text
	DurationMinutes pgtype.Int4
	Outcome         pgtype.Text
	SurgeonID       pgtype.Int4
}

func (q *Queries) CreateSessionSurgery(ctx context.Context, arg CreateSessionSurgeryParams) (SessionSurgery, error) {
	row := q.db.QueryRow(ctx, createSessionSurgery,
		arg.SessionID,
		arg.ProcedureName,
		arg.AnesthesiaType,
		arg.AnesthesiaAgent,
		arg.PreOpNotes,
		arg.IntraOpNotes,
		arg.PostOpNotes,
		arg.DurationMinutes,
		arg.Outcome,
		arg.SurgeonID,
	)
	var i SessionSurgery
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProcedureName,
		&i.AnesthesiaType,
		&i.AnesthesiaAgent,
		&i.PreOpNotes,
		&i.IntraOpNotes,
		&i.PostOpNotes,
		&i.DurationMinutes,
		&i.Outcome,
		&i.SurgeonID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionSurgeriesBySessionID = `-- name: DeleteSessionSurgeriesBySessionID :exec
DELETE FROM session_surgeries WHERE session_id = $1
`

func (q *Queries) DeleteSessionSurgeriesBySessionID(ctx context.Context, sessionID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionSurgeriesBySessionID, sessionID)
	return err
}

const deleteSessionSurgeryByID = `-- name: DeleteSessionSurgeryByID :exec
DELETE FROM session_surgeries WHERE id = $1
`

func (q *Queries) DeleteSessionSurgeryByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSessionSurgeryByID, id)
	return err
}

const findSessionSurgeriesBySessionID = `-- name: FindSessionSurgeriesBySessionID :many
SELECT id, session_id, procedure_name, anesthesia_type, anesthesia_agent, pre_op_notes, intra_op_notes, post_op_notes, duration_minutes, outcome, surgeon_id, created_at FROM session_surgeries WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) FindSessionSurgeriesBySessionID(ctx context.Context, sessionID int32) ([]SessionSurgery, error) {
	rows, err := q.db.Query(ctx, findSessionSurgeriesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSurgery
	for rows.Next() {
		var i SessionSurgery
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProcedureName,
			&i.AnesthesiaType,
			&i.AnesthesiaAgent,
			&i.PreOpNotes,
			&i.IntraOpNotes,
			&i.PostOpNotes,
			&i.DurationMinutes,
			&i.Outcome,
			&i.SurgeonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionSurgeryByID = `-- name: FindSessionSurgeryByID :one
SELECT id, session_id, procedure_name, anesthesia_type, anesthesia_agent, pre_op_notes, intra_op_notes, post_op_notes, duration_minutes, outcome, surgeon_id, created_at FROM session_surgeries WHERE id = $1
`

func (q *Queries) FindSessionSurgeryByID(ctx context.Context, id int32) (SessionSurgery, error) {
	row := q.db.QueryRow(ctx, findSessionSurgeryByID, id)
	var i SessionSurgery
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProcedureName,
		&i.AnesthesiaType,
		&i.AnesthesiaAgent,
		&i.PreOpNotes,
		&i.IntraOpNotes,
		&i.PostOpNotes,
		&i.DurationMinutes,
		&i.Outcome,
		&i.SurgeonID,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionSurgery = `-- name: UpdateSessionSurgery :one
UPDATE session_surgeries
SET session_id = $2, procedure_name = $3, anesthesia_type = $4, anesthesia_agent = $5,
    pre_op_notes = $6, intra_op_notes = $7, post_op_notes = $8, duration_minutes = $9, outcome = $10, surgeon_id = $11
WHERE id = $1
RETURNING id, session_id, procedure_name, anesthesia_type, anesthesia_agent, pre_op_notes, intra_op_notes, post_op_notes, duration_minutes, outcome, surgeon_id, created_at
`

type UpdateSessionSurgeryParams struct {
	ID              int32
	SessionID       int32
	ProcedureName   string
	AnesthesiaType  pgtype.Text
	AnesthesiaAgent pgtype.Text
	PreOpNotes      pgtype.Text
	IntraOpNotes    pgtype.Text
	PostOpNotes     pgtype.Text
	DurationMinutes pgtype.Int4
	Outcome         pgtype.Text
	SurgeonID       pgtype.Int4
}

func (q *Queries) UpdateSessionSurgery(ctx context.Context, arg UpdateSessionSurgeryParams) (SessionSurgery, error) {
	row := q.db.QueryRow(ctx, updateSessionSurgery,
		arg.ID,
		arg.SessionID,
		arg.ProcedureName,
		arg.AnesthesiaType,
		arg.AnesthesiaAgent,
		arg.PreOpNotes,
		arg.IntraOpNotes,
		arg.PostOpNotes,
		arg.DurationMinutes,
		arg.Outcome,
		arg.SurgeonID,
	)
	var i SessionSurgery
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProcedureName,
		&i.AnesthesiaType,
		&i.AnesthesiaAgent,
		&i.PreOpNotes,
		&i.IntraOpNotes,
		&i.PostOpNotes,
		&i.DurationMinutes,
		&i.Outcome,
		&i.SurgeonID,
		&i.CreatedAt,
	)
	return i, err
}
