// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_vaccinations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVaccinationHistoryBySpec = `-- name: CountVaccinationHistoryBySpec :one
SELECT COUNT(*) FROM session_vaccinations sv
JOIN medical_sessions ms ON ms.id = sv.session_id
WHERE ms.deleted_at IS NULL
  AND (cardinality($1::int[]) = 0 OR ms.pet_id = ANY($1::int[]))
  AND (cardinality($2::int[]) = 0 OR sv.vaccine_catalog_id = ANY($2::int[]))
  AND ($3::timestamptz IS NULL OR ms.visit_date >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR ms.visit_date <= $4::timestamptz)
`

type CountVaccinationHistoryBySpecParams struct {
	PetIds            []int32
	VaccineCatalogIds []int32
	DateFrom          pgtype.Timestamptz
	DateTo            pgtype.Timestamptz
}

func (q *Queries) CountVaccinationHistoryBySpec(ctx context.Context, arg CountVaccinationHistoryBySpecParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVaccinationHistoryBySpec,
		arg.PetIds,
		arg.VaccineCatalogIds,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSessionVaccination = `-- name: CreateSessionVaccination :one
INSERT INTO session_vaccinations (
    session_id, vaccine_catalog_id, batch_number, dose_number,
    expiration_date, site_of_injection, next_dose_date, reaction_notes, administered_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, vaccine_catalog_id, batch_number, dose_number, expiration_date, site_of_injection, next_dose_date, reaction_notes, administered_by, created_at
`

type CreateSessionVaccinationParams struct {
	SessionID        int32
	VaccineCatalogID int32
	BatchNumber      pgtype.Text
	DoseNumber       int32
	ExpirationDate   pgtype.Date
	SiteOfInjection  pgtype.Text
	NextDoseDate     pgtype.Date
	ReactionNotes    pgtype.Text
	AdministeredBy   pgtype.Int4
}

func (q *Queries) CreateSessionVaccination(ctx context.Context, arg CreateSessionVaccinationParams) (SessionVaccination, error) {
	row := q.db.QueryRow(ctx, createSessionVaccination,
		arg.SessionID,
		arg.VaccineCatalogID,
		arg.BatchNumber,
		arg.DoseNumber,
		arg.ExpirationDate,
		arg.SiteOfInjection,
		arg.NextDoseDate,
		arg.ReactionNotes,
		arg.AdministeredBy,
	)
	var i SessionVaccination
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.VaccineCatalogID,
		&i.BatchNumber,
		&i.DoseNumber,
		&i.ExpirationDate,
		&i.SiteOfInjection,
		&i.NextDoseDate,
		&i.ReactionNotes,
		&i.AdministeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionVaccinationByID = `-- name: DeleteSessionVaccinationByID :exec
DELETE FROM session_vaccinations WHERE id = $1
`

func (q *Queries) DeleteSessionVaccinationByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSessionVaccinationByID, id)
	return err
}

const deleteSessionVaccinationsBySessionID = `-- name: DeleteSessionVaccinationsBySessionID :exec
DELETE FROM session_vaccinations WHERE session_id = $1
`

func (q *Queries) DeleteSessionVaccinationsBySessionID(ctx context.Context, sessionID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionVaccinationsBySessionID, sessionID)
	return err
}

const findSessionVaccinationByID = `-- name: FindSessionVaccinationByID :one
SELECT id, session_id, vaccine_catalog_id, batch_number, dose_number, expiration_date, site_of_injection, next_dose_date, reaction_notes, administered_by, created_at FROM session_vaccinations WHERE id = $1
`

func (q *Queries) FindSessionVaccinationByID(ctx context.Context, id int32) (SessionVaccination, error) {
	row := q.db.QueryRow(ctx, findSessionVaccinationByID, id)
	var i SessionVaccination
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.VaccineCatalogID,
		&i.BatchNumber,
		&i.DoseNumber,
		&i.ExpirationDate,
		&i.SiteOfInjection,
		&i.NextDoseDate,
		&i.ReactionNotes,
		&i.AdministeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionVaccinationsBySessionID = `-- name: FindSessionVaccinationsBySessionID :many
SELECT id, session_id, vaccine_catalog_id, batch_number, dose_number, expiration_date, site_of_injection, next_dose_date, reaction_notes, administered_by, created_at FROM session_vaccinations WHERE session_id = $1 ORDER BY dose_number, created_at
`

func (q *Queries) FindSessionVaccinationsBySessionID(ctx context.Context, sessionID int32) ([]SessionVaccination, error) {
	rows, err := q.db.Query(ctx, findSessionVaccinationsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionVaccination
	for rows.Next() {
		var i SessionVaccination
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.VaccineCatalogID,
			&i.BatchNumber,
			&i.DoseNumber,
			&i.ExpirationDate,
			&i.SiteOfInjection,
			&i.NextDoseDate,
			&i.ReactionNotes,
			&i.AdministeredBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVaccinationHistoryBySpec = `-- name: FindVaccinationHistoryBySpec :many
SELECT sv.id, sv.session_id, sv.vaccine_catalog_id, sv.batch_number, sv.dose_number, sv.expiration_date, sv.site_of_injection, sv.next_dose_date, sv.reaction_notes, sv.administered_by, sv.created_at FROM session_vaccinations sv
JOIN medical_sessions ms ON ms.id = sv.session_id
WHERE ms.deleted_at IS NULL
  AND (cardinality($1::int[]) = 0 OR ms.pet_id = ANY($1::int[]))
  AND (cardinality($2::int[]) = 0 OR sv.vaccine_catalog_id = ANY($2::int[]))
  AND ($3::timestamptz IS NULL OR ms.visit_date >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR ms.visit_date <= $4::timestamptz)
ORDER BY ms.visit_date DESC
LIMIT $6 OFFSET $5
`

type FindVaccinationHistoryBySpecParams struct {
	PetIds            []int32
	VaccineCatalogIds []int32
	DateFrom          pgtype.Timestamptz
	DateTo            pgtype.Timestamptz
	PageOffset        int32
	PageLimit         int32
}

func (q *Queries) FindVaccinationHistoryBySpec(ctx context.Context, arg FindVaccinationHistoryBySpecParams) ([]SessionVaccination, error) {
	rows, err := q.db.Query(ctx, findVaccinationHistoryBySpec,
		arg.PetIds,
		arg.VaccineCatalogIds,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionVaccination
	for rows.Next() {
		var i SessionVaccination
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.VaccineCatalogID,
			&i.BatchNumber,
			&i.DoseNumber,
			&i.ExpirationDate,
			&i.SiteOfInjection,
			&i.NextDoseDate,
			&i.ReactionNotes,
			&i.AdministeredBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionVaccination = `-- name: UpdateSessionVaccination :one
UPDATE session_vaccinations
SET session_id = $2, vaccine_catalog_id = $3, batch_number = $4, dose_number = $5,
    expiration_date = $6, site_of_injection = $7, next_dose_date = $8, reaction_notes = $9, administered_by = $10
WHERE id = $1
RETURNING id, session_id, vaccine_catalog_id, batch_number, dose_number, expiration_date, site_of_injection, next_dose_date, reaction_notes, administered_by, created_at
`

type UpdateSessionVaccinationParams struct {
	ID               int32
	SessionID        int32
	VaccineCatalogID int32
	BatchNumber      pgtype.Text
	DoseNumber       int32
	ExpirationDate   pgtype.Date
	SiteOfInjection  pgtype.Text
	NextDoseDate     pgtype.Date
	ReactionNotes    pgtype.Text
	AdministeredBy   pgtype.Int4
}

func (q *Queries) UpdateSessionVaccination(ctx context.Context, arg UpdateSessionVaccinationParams) (SessionVaccination, error) {
	row := q.db.QueryRow(ctx, updateSessionVaccination,
		arg.ID,
		arg.SessionID,
		arg.VaccineCatalogID,
		arg.BatchNumber,
		arg.DoseNumber,
		arg.ExpirationDate,
		arg.SiteOfInjection,
		arg.NextDoseDate,
		arg.ReactionNotes,
		arg.AdministeredBy,
	)
	var i SessionVaccination
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.VaccineCatalogID,
		&i.BatchNumber,
		&i.DoseNumber,
		&i.ExpirationDate,
		&i.SiteOfInjection,
		&i.NextDoseDate,
		&i.ReactionNotes,
		&i.AdministeredBy,
		&i.CreatedAt,
	)
	return i, err
}
