// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionAttachment = `-- name: CreateSessionAttachment :one
INSERT INTO session_attachments (session_id, file_type, file_url, description, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, file_type, file_url, description, uploaded_by, created_at
`

type CreateSessionAttachmentParams struct {
	SessionID   int32
	FileType    string
	FileUrl     string
	Description pgtype.Text
	UploadedBy  pgtype.Int4
}

func (q *Queries) CreateSessionAttachment(ctx context.Context, arg CreateSessionAttachmentParams) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, createSessionAttachment,
		arg.SessionID,
		arg.FileType,
		arg.FileUrl,
		arg.Description,
		arg.UploadedBy,
	)
	var i SessionAttachment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FileType,
		&i.FileUrl,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionAttachmentByID = `-- name: DeleteSessionAttachmentByID :exec
DELETE FROM session_attachments WHERE id = $1
`

func (q *Queries) DeleteSessionAttachmentByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSessionAttachmentByID, id)
	return err
}

const deleteSessionAttachmentsBySessionID = `-- name: DeleteSessionAttachmentsBySessionID :exec
DELETE FROM session_attachments WHERE session_id = $1
`

func (q *Queries) DeleteSessionAttachmentsBySessionID(ctx context.Context, sessionID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionAttachmentsBySessionID, sessionID)
	return err
}

const findSessionAttachmentByID = `-- name: FindSessionAttachmentByID :one
SELECT id, session_id, file_type, file_url, description, uploaded_by, created_at FROM session_attachments WHERE id = $1
`

func (q *Queries) FindSessionAttachmentByID(ctx context.Context, id int32) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, findSessionAttachmentByID, id)
	var i SessionAttachment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FileType,
		&i.FileUrl,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionAttachmentsBySessionID = `-- name: FindSessionAttachmentsBySessionID :many
SELECT id, session_id, file_type, file_url, description, uploaded_by, created_at FROM session_attachments WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) FindSessionAttachmentsBySessionID(ctx context.Context, sessionID int32) ([]SessionAttachment, error) {
	rows, err := q.db.Query(ctx, findSessionAttachmentsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAttachment
	for rows.Next() {
		var i SessionAttachment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FileType,
			&i.FileUrl,
			&i.Description,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionAttachment = `-- name: UpdateSessionAttachment :one
UPDATE session_attachments
SET session_id = $2, file_type = $3, file_url = $4, description = $5, uploaded_by = $6
WHERE id = $1
RETURNING id, session_id, file_type, file_url, description, uploaded_by, created_at
`

type UpdateSessionAttachmentParams struct {
	ID          int32
	SessionID   int32
	FileType    string
	FileUrl     string
	Description pgtype.Text
	UploadedBy  pgtype.Int4
}

func (q *Queries) UpdateSessionAttachment(ctx context.Context, arg UpdateSessionAttachmentParams) (SessionAttachment, error) {
	row := q.db.QueryRow(ctx, updateSessionAttachment,
		arg.ID,
		arg.SessionID,
		arg.FileType,
		arg.FileUrl,
		arg.Description,
		arg.UploadedBy,
	)
	var i SessionAttachment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FileType,
		&i.FileUrl,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
